### ISSUE TITLE
Test Data Successfully Run: Log below

### ISSUE THREAD

**Issue by akadrhouse** [demis001/raslpipe#12]
(raslpipe)john@john-VirtualBox:~/raslpipe-1.2-alpha$ raslpipe_cli --flowchart outdir_pipeline_stages_to_run.ps -o outdir -f ./testData -p ./testData/160219_tox_3d_manifest.csv
outdir
/home/john/raslpipe-1.2-alpha/testData
/home/john/raslpipe-1.2-alpha/testData/160219_tox_3d_manifest.csv
4
outdir/logs
outdir/result
 Starting time ..... :1467819597.79

---

Tasks which will be run:

Task enters queue = "mkdir('outdir/result/Genome')   before raslpipe.main.indexGenomeFile " 
Task enters queue = "mkdir('outdir',   'outdir/result',   'outdir/logs',   'outdir/result/tempFolder')   before raslpipe.main.prepare_analysis " 
Completed Task = "mkdir('outdir/result/Genome')   before raslpipe.main.indexGenomeFile " 
Completed Task = "mkdir('outdir',   'outdir/result',   'outdir/logs',   'outdir/result/tempFolder')   before raslpipe.main.prepare_analysis " 
Task enters queue = 'raslpipe.main.prepare_analysis' 
('Stage1: Copy', '/home/john/raslpipe-1.2-alpha/testData/160219_tox_3d_manifest.csv', ' to ', 'outdir/result/160219_tox_3d_manifest.csv')
Completed Task = 'raslpipe.main.prepare_analysis' 
Task enters queue = 'raslpipe.main.prepareDB_file' 
Task enters queue = 'raslpipe.main.create_gtf_file' 
Stage 2: Creating DB file from probe file ...
outdir/result/160219_tox_3d_manifest.csv
A2M_12371,1,A2M,CTTCAGGTTCAACCAACAGAGGCTTGATGACTGTGTCTTTCCTTCCGTGT,NM_000014,NM_000014,2838
AARS_3,1,AARS,TGCAGACACATCCTTGCCACCACCTTTACCGTCCATCAAGCCTGACACCT,NM_001605,NM_001605,2924
AASDHPPT_21936,1,AASDHPPT,TCATCAGACGACCAGCCATGGCTGCCTTAGCGTCCCGGGCAAAGACGAAC,NM_015423,NM_015423,345
AATF_26432,1,AATF,GGCTCAGGTTTGCCAAGAACTCGATAGACAGAGCGCTTGGTCTGTGTCCT,NM_012138,NM_012138,1525
ABCA6_22690,1,ABCA6,GGCTCAGCACAAAACACAACTTTCTCGTGATTCCTGCTGTTAATTTCTGC,NM_080284,NM_080284,4454
ABCA6_28368,1,ABCA6,GGTTAAAGTTATGCTTCACTGCTTCTAATTTGTGAAAGGTCTGTGATAGA,NM_080284,NM_080284,4889
ABCB1_12,1,ABCB1,AAAGAGTTTCTGTATGGTACCTGCAAACTCTGAGCATACATATGTTCAAA,NM_000927,NM_000927,3288
ABCB10_14348,1,ABCB10,TCCTTGGTCAAGAACAGCAACCATATTAGCATTCTTAATGGTGGACAGAC,NM_012089,NM_012089,2164
ABCB11_21010,1,ABCB11,ACAAGATGACCAGGCTCAGCTTCCAGCTAAAGGAGAAGGCAATGATCATG,NM_003742,NM_003742,2842
ABCB6_26787,1,ABCB6,CAGCCATCCTTGATGACGAGGATCTGGTCAGCATTGACCACAGTTGAGAG,NM_005689,NM_005689,2719
ABCC1_15868,1,ABCC1,TGTTGATGCCATCGATGATGATCTCTCCTTCGGCAGACTCGTTGATCCGA,NM_004996,NM_004996,4247
ABCC2_22,1,ABCC2,CAGTTCTTCAGGGCTGCCGCACTCTATAATCTTCCCGTTGTCTAGGACCA,NM_000392,NM_000392,4810
ABCC2_26620,1,ABCC2,GCTACCGATGTCACAAGTGATCCCTCTGAGGACCAGATCCAGCTCAGGTC,NM_000392,NM_000392,4225
ABCC3_23353,1,ABCC3,TGTCCTTGGAGAAGCAGTTCAGGATGCGGCCTGATGGTGTGGTGTCAAAG,NM_003786,NM_003786,3306
ABCC3_26788,1,ABCC3,AGCACCTTGATGCCGTTCAGGATCTCACTCATCAGCTTGATGCGCGAGTC,NM_001144070,NM_001144070,1582
ABCC4_16668,1,ABCC4,GCTGTCCATTGGAAGTGTTTGTAACCATGTGGTCAGTGTGACCAATATGT,NM_005845,NM_005845,4075
ABCC4_26789,1,ABCC4,GGTTACATTTCCTCCTCCATTTACAGTGACATTTAGCATACTTTGTTTGT,NM_001105515,NM_001105515,2400
ABCC5_26,1,ABCC5,CTCTCTAGTCTTCTGCAGTTCACGTCAGAAGACTCGTGCTTGGACAGAGA,NM_001023587,NM_005688+NM_001023587,617
ABCF1_35,1,ABCF1,AGCACCCTTGTATTCATTGATGGCCTCCCCTAGAGCATCAATAGACTCTA,NM_001025091,NM_001025091+NM_001090,2468
Stage 3: Creating custom gtf file from manifest file ...
outdir/result/160219_tox_3d_manifest.csv
Completed Task = 'raslpipe.main.prepareDB_file' 
Task enters queue = 'raslpipe.main.indexGenomeFile' 
Stage 4: Creating genome index file from the probe fasta file ....
outdir/result/160219_tox_3d.fa
STAR  --runMode genomeGenerate  --genomeDir  outdir/result/Genome  --genomeFastaFiles  outdir/result/160219_tox_3d.fa  --runThreadN  4  --genomeSAindexNbases 2 2>&1 | tee -a outdir/result/Genome/index_STAR_genomeFile.log
Completed Task = 'raslpipe.main.create_gtf_file' 
Completed Task = 'raslpipe.main.indexGenomeFile' 
Task enters queue = 'raslpipe.main.map_to_probes' 

---

Stage 5: Map sequence fastq file to the indexed genome file ... 
/home/john/raslpipe-1.2-alpha/testData/A01B_S25_All_R1_001.fastq.gz
/home/john/raslpipe-1.2-alpha/testData/A01B_S25_All_R1_001.fastq.bam
outdir/result/Genome
/home/john/raslpipe-1.2-alpha/outdir/result/tempFolder/A01B_S25_All_R1_001.fastq
outdir/result/160219_tox_3d.gtf

---

STAR  --genomeDir  outdir/result/Genome  --readFilesIn  /home/john/raslpipe-1.2-alpha/testData/A01B_S25_All_R1_001.fastq.gz  --readFilesCommand zcat  --runThreadN   4  --outFileNamePrefix  /home/john/raslpipe-1.2-alpha/outdir/result/tempFolder/A01B_S25_All_R1_001.fastq  --outSAMtype BAM SortedByCoordinate  --quantMode GeneCounts  --sjdbGTFfile  outdir/result/160219_tox_3d.gtf   --genomeLoad NoSharedMemory

---

Stage 5: Map sequence fastq file to the indexed genome file ... 
/home/john/raslpipe-1.2-alpha/testData/A02B_S27_All_R1_001.fastq.gz
/home/john/raslpipe-1.2-alpha/testData/A02B_S27_All_R1_001.fastq.bam
outdir/result/Genome
/home/john/raslpipe-1.2-alpha/outdir/result/tempFolder/A02B_S27_All_R1_001.fastq
outdir/result/160219_tox_3d.gtf

---

STAR  --genomeDir  outdir/result/Genome  --readFilesIn  /home/john/raslpipe-1.2-alpha/testData/A02B_S27_All_R1_001.fastq.gz  --readFilesCommand zcat  --runThreadN   4  --outFileNamePrefix  /home/john/raslpipe-1.2-alpha/outdir/result/tempFolder/A02B_S27_All_R1_001.fastq  --outSAMtype BAM SortedByCoordinate  --quantMode GeneCounts  --sjdbGTFfile  outdir/result/160219_tox_3d.gtf   --genomeLoad NoSharedMemory

---

Stage 5: Map sequence fastq file to the indexed genome file ... 
/home/john/raslpipe-1.2-alpha/testData/A03B_S29_All_R1_001.fastq.gz
/home/john/raslpipe-1.2-alpha/testData/A03B_S29_All_R1_001.fastq.bam
outdir/result/Genome
/home/john/raslpipe-1.2-alpha/outdir/result/tempFolder/A03B_S29_All_R1_001.fastq
outdir/result/160219_tox_3d.gtf

---

STAR  --genomeDir  outdir/result/Genome  --readFilesIn  /home/john/raslpipe-1.2-alpha/testData/A03B_S29_All_R1_001.fastq.gz  --readFilesCommand zcat  --runThreadN   4  --outFileNamePrefix  /home/john/raslpipe-1.2-alpha/outdir/result/tempFolder/A03B_S29_All_R1_001.fastq  --outSAMtype BAM SortedByCoordinate  --quantMode GeneCounts  --sjdbGTFfile  outdir/result/160219_tox_3d.gtf   --genomeLoad NoSharedMemory
Completed Task = 'raslpipe.main.map_to_probes' 
Task enters queue = 'raslpipe.main.alignment_summary' 
Task enters queue = 'raslpipe.main.format_count' 

---

Stage 8: Generate Alingmnet summary ....

---

---

Stage 8: Generate Alingmnet summary ....

---

---

Stage 8: Generate Alingmnet summary ....

---

Completed Task = 'raslpipe.main.alignment_summary' 
Task enters queue = 'raslpipe.main.combine_alignment_summary' 

---

Stage 6: Formatting count file ... 
outdir/result/tempFolder/A01B_S25_All_R1_001.fastqReadsPerGene.out.tab
outdir/result/tempFolder/A01B_S25_All_R1_001.fastqReadsPerGene.out.txt

---

---

Stage 6: Formatting count file ... 
outdir/result/tempFolder/A02B_S27_All_R1_001.fastqReadsPerGene.out.tab
outdir/result/tempFolder/A02B_S27_All_R1_001.fastqReadsPerGene.out.txt

---

---

Stage 6: Formatting count file ... 
outdir/result/tempFolder/A03B_S29_All_R1_001.fastqReadsPerGene.out.tab
outdir/result/tempFolder/A03B_S29_All_R1_001.fastqReadsPerGene.out.txt

---

Completed Task = 'raslpipe.main.format_count' 
Task enters queue = 'raslpipe.main.combine_count_data' 

---

Stage 9: Aggrigate alignment summary ....

---

---

Stage 7: Combining count data ...

---

Completed Task = 'raslpipe.main.combine_alignment_summary' 
Task enters queue = 'raslpipe.main.plot_alignment_summary' 

---

Stage 10: Plot alignment summary ...
outdir/resultDATA_alignment_summary.csv
outdir/resultDATA_alignment_summary.png

---

Completed Task = 'raslpipe.main.combine_count_data' 
category     object
A01B_S25    float64
A02B_S27    float64
A03B_S29    float64
dtype: object
                                   category     A01B_S25    A02B_S27  \
0                     Number_of_input_reads  1991.000000  1240.00000  
1              Uniquely_mapped_reads_number  1742.000000  1051.00000  
2                    Uniquely_mapped_reads%    87.490000    84.76000  
3                     Average_mapped_length    49.700000    49.72000  
4  Number_of_reads_mapped_to_multiple_loci%     0.100452     0.16129  
5                 Reads_unmapped_too_short%    12.410000    15.08000   

```
  A03B_S29  
```

0  2242.000000  
1  2022.000000  
2    90.190000  
3    49.710000  
4     0.312221  
5     9.500000  
                                   category sampleName      Value
0                    Uniquely_mapped_reads%   A01B_S25  87.490000
1  Number_of_reads_mapped_to_multiple_loci%   A01B_S25   0.100452
2                 Reads_unmapped_too_short%   A01B_S25  12.410000
3                    Uniquely_mapped_reads%   A02B_S27  84.760000
4  Number_of_reads_mapped_to_multiple_loci%   A02B_S27   0.161290
5                 Reads_unmapped_too_short%   A02B_S27  15.080000
6                    Uniquely_mapped_reads%   A03B_S29  90.190000
7  Number_of_reads_mapped_to_multiple_loci%   A03B_S29   0.312221
8                 Reads_unmapped_too_short%   A03B_S29   9.500000
outdir
resultDATA_alignment_summary.png
Completed Task = 'raslpipe.main.plot_alignment_summary' 
.....................outdir/result
Time to complete the task .....0:00:32
(raslpipe)john@john-VirtualBox:~/raslpipe-1.2-alpha$

**Comment by demis001** [comment]
Thank you John!

KUDOS!
