### ISSUE TITLE
installing python on raslpipe environment

### ISSUE THREAD

**Issue by jshousephd** [demis001/raslpipe#16]
![image](https://cloud.githubusercontent.com/assets/7661058/21316578/5e12b386-c5cf-11e6-878a-bdaa757cc998.png)

**Comment by jshousephd** [comment]
![image](https://cloud.githubusercontent.com/assets/7661058/21316702/f72a9afc-c5cf-11e6-85fb-a0e1dc612641.png)

**Comment by demis001** [comment]
@jshousephd 

Try it now, it was the pip version issue. I have added the logic to fix the version issue

`
@task                                                                            
def install_python_dependencies():                                               
     import pip                                                                   
     if pip.__version__ > 6.0:                                                    
     ¦   sh('pip install -r requirements-dev.txt')                                
     else:                                                                        
     ¦   sh('pip install -r requirements-dev.txt  --cache-dir raslpipe/download/.pip_cache')
`
@demis001

**Comment by demis001** [comment]
@jshousephd 

Make sure to clone the directory again and follow the new install doc

**Comment by jshousephd** [comment]
New Issue:
-packages (from -r requirements-dev.txt (line 39))
Collecting image (from -r requirements-dev.txt (line 40))
  Downloading image-1.5.5.tar.gz
Collecting HTSeq (from -r requirements-dev.txt (line 41))
  Downloading HTSeq-0.6.1.tar.gz (226kB)
    100% |████████████████████████████████| 235kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Setup script for HTSeq: Failed to import 'numpy'.
    Please install numpy and then try again to install HTSeq.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-69XF7n/HTSeq/

**Comment by demis001** [comment]
@jshousephd 

Numpy failed to install from requirement file. I have implemented separate routine to install it. Now it will work.
The issue was described here: http://stackoverflow.com/questions/11015692/pip-fails-to-install-packages-from-requirements-txt

Let me know if you found other issue in the later time.
