### ISSUE TITLE
After the make install command

### ISSUE THREAD

**Issue by jshousephd** [demis001/raslpipe#19]
build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python2.7/distutils/cmd.py", line 311, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python2.7/distutils/dist.py", line 845, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/john/temposeqcount/temposeqcount/local/lib/python2.7/site-packages/setuptools/dist.py", line 491, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/john/temposeqcount/temposeqcount/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
        return self.resolve()
      File "/home/john/temposeqcount/temposeqcount/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/john/temposeqcount/temposeqcount/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 12, in <module>
        from six.moves import map, filter, filterfalse
    ImportError: cannot import name filterfalse
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-H6WIzk/Paver/

Captured Task Output:
---------------------

---> pavement.install
---> pavement.prepare
---> pavement.install_dependencies
---> pavement.install_python_dependencies
pip install numpy
pip install -r requirements-dev.txt

Build failed running pavement.install: Subprocess return code: 1
Makefile:22: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by demis001** [comment]
Can you paste the output of the following two commands on shell terminal.

`cat /etc/*release`

AND python version

`python -v`

@demis001

**Comment by jshousephd** [comment]
john@john-VirtualBox:~/temposeqcount$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
john@john-VirtualBox:~/temposeqcount$ python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
import _locale # builtin
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so

**Comment by demis001** [comment]
Thanks,

I will initialize ubuntu/Xenial64 and let you know.

https://vagrantcloud.com/ubuntu

@demis001

**Comment by demis001** [comment]
This throw an error:

`sudo apt-get install python-dev g++ libjpeg-dev pkg-config ghostscript git gfortran zlib1g-dev build-essential libopenblas-base libopenblas-dev liblapack-dev python-sphinx libncurses5  libncurses5-dev libpng12-dev libfreetype6-dev`

Then:  I did this to fix it, may be specific to my platform
`sudo apt-get update`

Then,
`sudo apt-get install python-dev g++ libjpeg-dev pkg-config ghostscript git gfortran zlib1g-dev build-essential libopenblas-base libopenblas-dev liblapack-dev python-sphinx libncurses5  libncurses5-dev libpng12-dev libfreetype6-dev`

SUCCESS!!

`update-alternatives: using /usr/share/docutils/scripts/python2/rstpep2html to provide /usr/bin/rstpep2html (rstpep2html) in auto mode
Setting up python-sphinx (1.3.6-2ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
`

@demis001

**Comment by jshousephd** [comment]
john@john-VirtualBox:~/temposeqcount$ rm -rf temposeqcount
john@john-VirtualBox:~/temposeqcount$ clone https://github.com/demis001/temposeqcount.git
clone: command not found
john@john-VirtualBox:~/temposeqcount$ git clone https://github.com/demis001/temposeqcount.git
Cloning into 'temposeqcount'...
remote: Counting objects: 664, done.
remote: Total 664 (delta 0), reused 0 (delta 0), pack-reused 664
Receiving objects: 100% (664/664), 3.62 MiB | 426.00 KiB/s, done.
Resolving deltas: 100% (391/391), done.
Checking connectivity... done.
john@john-VirtualBox:~/temposeqcount$ make install
python ./virtualenv-15.1.0/virtualenv.py temposeqcount && \
. temposeqcount/bin/activate && \
pip install -U Paver sphinx_rtd_theme && \
python setup.py install
New python executable in /home/john/temposeqcount/temposeqcount/bin/python
Installing setuptools, pip, wheel...done.
Collecting Paver
  Using cached Paver-1.2.4-py2.py3-none-any.whl
Collecting sphinx_rtd_theme
  Using cached sphinx_rtd_theme-0.2.4-py2.py3-none-any.whl
Installing collected packages: Paver, sphinx-rtd-theme
Successfully installed Paver-1.2.4 sphinx-rtd-theme-0.2.4
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    'metadata', os.path.join(CODE_DIRECTORY, 'metadata.py'))
IOError: [Errno 2] No such file or directory
Makefile:22: recipe for target 'install' failed
make: *** [install] Error 1
john@john-VirtualBox:~/temposeqcount$

**Comment by jshousephd** [comment]
Sorry figured out that last error. Redoing the make install now.

**Comment by jshousephd** [comment]
I got it to work. You might want to put a apt-get update at the beginning of your install process.

**Comment by demis001** [comment]
@jshousephd 

Thank you ! forgot to update that
@demis001
