### ISSUE TITLE
Exception #1 ZeroDivisionError(float division by zero)

### ISSUE THREAD

**Issue by Biologic3** [demis001/raslpipe#24]
Hello,

I am getting the following error during "Stage 8: Generate Alignment summary" when I try to run the temposeqcount pipeline on Ubuntu 16.0.4. I followed the installation guide to setup my virtualenv. My -f directory has the fastq.qz files properly labeled and the -r manifest.csv file is formatted properly just like the manifest in the testData. I think the problem occurs during "Stage 5: Map sequence fastq file to the indexed genome file" because my fastqLog.final.out files show that 0 reads are inputted. Is there something wrong with my STAR version? 

![screen shot 2018-11-25 at 2 14 48 am](https://user-images.githubusercontent.com/45337999/48982502-68078100-f0b1-11e8-9951-86cb7d153151.png)

Here is my Log.out file
[Logout.txt](https://github.com/demis001/temposeqcount/files/2613399/Logout.txt)

**Comment by demis001** [comment]
Did you resolve this? It seems you closed the issue? Sorry for delayed response, it was Sunday here.
