### ISSUE TITLE
Is 'attennuation' and 'distance from 5 end' columns from manifest file used by temposeqcount tool?

### ISSUE THREAD

**Issue by Agpa88** [demis001/raslpipe#27]
Dear @demis001, 

I have just learnt from Biospyder representative that they don't provide any more "Distance_from_5_Prime_End_of_mRNA" column in the manifest file. Moreover "Attenuation_Correction_Factor" column is provided only upon request. It means that their standard manifest file consists of only 5 columns (7 is required by temposeqcount script).
What I did, I tricked the temposeqcount script and provided mocking columns for "Distance_from_5_Prime_End_of_mRNA" and "Attenuation_Correction_Factor" filling them with ones and it worked - the output is the same compared to the manifest file with the 2 rightful columns. So it seems that these two columns they are not used during pseudo transcriptome creation and counting, am I right? I am just wondering whether my approach may result in false results in some cases?
Best, 
Agnieszka

**Comment by jshousephd** [comment]
@Agpa88 Sorry, I thought your question had been addressed. The fix you did to the manifest file should have no impact on the results from the alignment/mapping of reads.
Best regards,
john

**Comment by Agpa88** [comment]
Dear John, 
Thanks a lot!!
Best, 
Agnieszka
